services:
  postgres:
    image: postgres:13
    container_name: myapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nodeapp:
    build: .
    container_name: aWebsite
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGHOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${PGPORT}
    depends_on:
      - postgres

volumes:
  postgres_data:
